### ISSUE TITLE
[joss review] community guidelines

### ISSUE THREAD

**Issue by mschubert** [jspaezp/sctree#2]
This issue is part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/2061).

The JOSS checklist states:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Please provide this information (usually done in the `README` or `CONTRIBUTING.md`)

**Comment by natallah** [comment]
I added Contribute.md

Thank you!

**Comment by jspaezp** [comment]
I will mark the issue as closed, and say that it was addressed in 4bbc6825f45f3738c63618592b9b14393c9c755c

Thank you very much for the note and thanks @natallah for adding the document
Let me know if any additional specifications are required.

**Comment by mschubert** [comment]
This may seem a bit nitpicking (and is not required for JOSS, so feel free to ignore), but note that the file name `CONTIRUBUTING.md` (upper/lower case is I think irrelevant) will be recognized by Github (and other machine parsers) as contribution guidelines. `Contribute.md` will not.

If you click on Insights>Community, you will see what I mean.

**Comment by jspaezp** [comment]
hello @mschubert, I have added this change in d2d85d41d014b407bdb632dd2d4f0d9543b9738e
