### ISSUE TITLE
[joss review] automated tests

### ISSUE THREAD

**Issue by mschubert** [jspaezp/sctree#3]
This issue is part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/2061).

Can you please make sure your package passes [its tests](https://travis-ci.org/jspaezp/sctree)?

Currently, there is a URL error on Travis for vignette building.

**Comment by natallah** [comment]
Hi! Sorry about that... we will fix it asap

**Comment by jspaezp** [comment]
I have pushed several commits that address these issues. 
Currently all checks and tests pass on my desktop and docker environments. 
I will leave this open until it successfully passes the tests in Travis

**Comment by jspaezp** [comment]
@mschubert @natallah 
Tests have passed on the `bioc-release` and `bioc-devel` branches! There were indeed a couple of things that needed fixing due to a change in the request structure for santa cruz antibodies and an issue where special characters made latex fail when generating the manual.

https://travis-ci.org/jspaezp/sctree/jobs/645977617

please let me know if any additional changes are required.

**Comment by jspaezp** [comment]
Will mark as closed, since all the builds complete successfully in travis.

**Comment by mschubert** [comment]
@jspaezp your build seems to be failing again: https://travis-ci.org/jspaezp/sctree/builds/651358734

**Comment by jspaezp** [comment]
Looking at the log, it seems like the part failing is not in my tests on *bioc-devel* ...

```
* installing *source* package ‘GenomeInfoDb’ ...

** using staged installation

** R

** inst

** byte-compile and prepare package for lazy loading

Error: package or namespace load failed for ‘S4Vectors’:

 .onLoad failed in loadNamespace() for 'S4Vectors', details:

  call: validObject(.Object)

  error: invalid class “LLint” object: superclass "integer_OR_LLint" not defined in the environment of the object's class

Error: package ‘S4Vectors’ could not be loaded

Execution halted

ERROR: lazy loading failed for package ‘GenomeInfoDb’

* removing ‘/home/travis/R/Library/GenomeInfoDb’

Error in i.p(...) : 

  (converted from warning) installation of package ‘GenomeInfoDb’ had non-zero exit status

Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p

Execution halted
```

**Comment by jspaezp** [comment]
on the other hand the "bioc-stable" release works fine

https://travis-ci.org/jspaezp/sctree/jobs/654457775
