### ISSUE TITLE
[joss review] Installation functionality

### ISSUE THREAD

**Issue by jenzopr** [jspaezp/sctree#4]
Hi @jspaezp!

This issue is part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/2061).

Can you please update the installation instructions in the README(.md|.Rmd)? The URL to the Git repository given there is not valid anymore. Also, consider switching to `remotes::install_github` instead of a `git checkout` and `devtools::install`. 

Using `remotes::install_github("jspaezp/sctree")` works fine and without errors for me.

**Comment by jspaezp** [comment]
Hello @jenzopr 

Thank you for noticing this!

addressed it in 39b00cc09be9e800f22dbcbb5fb5710149ca0704
(also created a hotfix branch for the fixes involved in the review)

Kindest wishes,
Sebastian

**Comment by mschubert** [comment]
I'm a bit confused about your installation instructions. Why do you want your users to clone manually and then install the package using `devtools`?

Wouldn't it be easier to do either a

```r
devtools::install_github("jspaezp/sctree")
```

or

```r
remotes::install_github("jspaezp/sctree")
```

without the manual cloning & installing steps?

**Comment by jspaezp** [comment]
Hello @mschubert ! 

I add that option in case the user wants to modify the repository and install the modified version. Indeed using remotes is the easiest way to do it.

Do you believe it would be required for me to remove it? Since it is a fairly restricted use-case

**Comment by mschubert** [comment]
Your current instructions are valid, so keeping your manual cloning and installation to will not block your paper's acceptance (so this is your decision).

However, I don't understand your reasoning. I'd think the installation instructions are there primarily to help novice users; more experienced package developers (who are the ones that may want to change your code) will already know that they can clone manually.

**Comment by jspaezp** [comment]
Hello @mschubert,

after thinking about it i decided to move the manual install instructions to the contributions file from the readme. Changes are done in 6a5fda3075217a691809019afdc612b18c44306c

Kindest wishes,
Sebastian

@natallah
