### ISSUE TITLE
[joss review] documentation

### ISSUE THREAD

**Issue by mschubert** [jspaezp/sctree#8]
This issue is part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/2061).

I see that you have compiled your documentation into a website: https://jspaezp.github.io/sctree/

Please also link this as Github URL and/or from the README, otherwise your users will not find it.

**Comment by mschubert** [comment]
Minor webpage: the "home" and "getting started" links link to the same information; provide this only once to not confuse users?

**Comment by mschubert** [comment]
https://jspaezp.github.io/sctree/reference/index.html

API documentation could also be improved: The title of many functions is equal to their name. This does not help a user to know what these functions are doing. Maybe provide more descriptive titles? (and do not list internal functions there)

**Comment by mschubert** [comment]
Also minor README/docs: You are `require(...)` to load packages, but do not check for a return value. 

This may lead to confusing errors for users if the package is not installed: `require` will only warn, and the script will produce an error elsewhere (that may not sound like the source is a missing package). If you use `library(...)` instead, a script will terminate with an error if the package is not installed.

**Comment by jspaezp** [comment]
Hello @mschubert, I can definitely agree with all of these, I am compiling this into a todo list.
Will keep you posted as I go though it.

TODO:

- [x] link this as Github URL and/or from the README, otherwise your users will not find it.
- [x] the "home" and "getting started" links link to the same information. Fix it.
- [x] provide more descriptive titles in the documentation
- [x] change `require` to `library` in documentation.

@natallah

**Comment by jspaezp** [comment]
Commit b402fbe9eaaa17c352053f65c953b173c4f0e5f5 adds the reference to the website, and changes some of the titles in the reference section of the documentation. It also changes in all vignettes the `require` for the `library` function.

@natallah and @mschubert

**Comment by jspaezp** [comment]
Home and getting started section in the pkgdown website have been resolved in ffa30082ed60cc7dc0d9bdd26197ebaedbaa4bfe

Descriptive titles to the documentation in the reference section is added on commit dc788fd33839397c5528148b7a6b8c4da276a62b

This completes the TODO list for this issue, so I will go ahead and close it.
@mschubert @natallah
